name: Update badges

on:
  schedule:
    # Runs at 6am GMT+06 every day
    - cron: "0 6 * * *"
  workflow_dispatch: # Add this to enable manual trigger
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
